const countryCurrency: Record<string, string> = {
    "Albania": "ALL",
    "Andorra": "EUR",
    "Austria": "EUR",
    "Belarus": "BYN",
    "Belgium": "EUR",
    "Bosnia and Herzegovina": "BAM",
    "Bulgaria": "EUR",
    "Croatia": "EUR",
    "Cyprus": "EUR",
    "Czech Republic": "CZK",
    "Denmark": "DKK",
    "Estonia": "EUR",
    "Finland": "EUR",
    "France": "EUR",
    "Georgia": "GEL",
    "Germany": "EUR",
    "Greece": "EUR",
    "Hungary": "HUF",
    "Iceland": "ISK",
    "Ireland": "EUR",
    "Italy": "EUR",
    "Kazakhstan": "KZT",
    "Kosovo": "EUR",
    "Latvia": "EUR",
    "Liechtenstein": "CHF",
    "Lithuania": "EUR",
    "Luxembourg": "EUR",
    "Malta": "EUR",
    "Moldova": "MDL",
    "Monaco": "EUR",
    "Montenegro": "EUR",
    "Netherlands": "EUR",
    "North Macedonia": "MKD",
    "Norway": "NOK",
    "Poland": "PLN",
    "Portugal": "EUR",
    "Romania": "RON",
    "Russia": "RUB",
    "San Marino": "EUR",
    "Serbia": "RSD",
    "Slovak Republic": "EUR",
    "Slovenia": "EUR",
    "Spain": "EUR",
    "Sweden": "SEK",
    "Switzerland": "CHF",
    "Turkey": "TRY",
    "Ukraine": "UAH",
    "United Kingdom": "GBP",
    "Vatican City": "EUR"
};


export default function currencyMap(country: string) {
    return countryCurrency[country];
}