const countryCurrency: Record<string, string> = {
    "Albania": "ALL",
    "Andorra": "EUR",
    "Austria": "EUR",
    "Belarus": "BYN",
    "Belgium": "EUR",
    "Bosnia and Herzegovina": "BAM",
    "Bulgaria": "EUR",
    "Croatia": "EUR",
    "Cyprus": "EUR",
    "Czech Republic": "CZK",
    "Denmark": "DKK",
    "Estonia": "EUR",
    "Finland": "EUR",
    "France": "EUR",
    "Georgia": "GEL",
    "Germany": "EUR",
    "Greece": "EUR",
    "Hungary": "HUF",
    "Iceland": "ISK",
    "Ireland": "EUR",
    "Italy": "EUR",
    "Kazakhstan": "KZT",
    "Kosovo": "EUR",
    "Latvia": "EUR",
    "Liechtenstein": "CHF",
    "Lithuania": "EUR",
    "Luxembourg": "EUR",
    "Malta": "EUR",
    "Moldova": "MDL",
    "Monaco": "EUR",
    "Montenegro": "EUR",
    "Netherlands": "EUR",
    "North Macedonia": "MKD",
    "Norway": "NOK",
    "Poland": "PLN",
    "Portugal": "EUR",
    "Romania": "RON",
    "Russia": "RUB",
    "San Marino": "EUR",
    "Serbia": "RSD",
    "Slovak Republic": "EUR",
    "Slovenia": "EUR",
    "Spain": "EUR",
    "Sweden": "SEK",
    "Switzerland": "CHF",
    "Turkey": "TRY",
    "Ukraine": "UAH",
    "United Kingdom": "GBP",
    "Vatican City": "EUR",

    // --- Rest of the world ---
    "Afghanistan": "AFN",
    "Algeria": "DZD",
    "Angola": "AOA",
    "Antigua and Barbuda": "XCD",
    "Argentina": "ARS",
    "Armenia": "AMD",
    "Australia": "AUD",
    "Azerbaijan": "AZN",
    "Bahamas": "BSD",
    "Bahrain": "BHD",
    "Bangladesh": "BDT",
    "Barbados": "BBD",
    "Belize": "BZD",
    "Benin": "XOF",
    "Bhutan": "BTN",
    "Bolivia": "BOB",
    "Botswana": "BWP",
    "Brazil": "BRL",
    "Brunei": "BND",
    "Burkina Faso": "XOF",
    "Burundi": "BIF",
    "Cabo Verde": "CVE",
    "Cambodia": "KHR",
    "Cameroon": "XAF",
    "Canada": "CAD",
    "Central African Republic": "XAF",
    "Chad": "XAF",
    "Chile": "CLP",
    "China": "CNY",
    "Colombia": "COP",
    "Comoros": "KMF",
    "Congo (Republic)": "XAF",
    "Congo (Democratic Republic)": "CDF",
    "Costa Rica": "CRC",
    "Côte d'Ivoire": "XOF",
    "Cuba": "CUP",
    "Djibouti": "DJF",
    "Dominica": "XCD",
    "Dominican Republic": "DOP",
    "Ecuador": "USD",
    "Egypt": "EGP",
    "El Salvador": "USD",
    "Equatorial Guinea": "XAF",
    "Eritrea": "ERN",
    "Eswatini": "SZL",
    "Ethiopia": "ETB",
    "Fiji": "FJD",
    "Gabon": "XAF",
    "Gambia": "GMD",
    "Ghana": "GHS",
    "Grenada": "XCD",
    "Guatemala": "GTQ",
    "Guinea": "GNF",
    "Guinea-Bissau": "XOF",
    "Guyana": "GYD",
    "Haiti": "HTG",
    "Honduras": "HNL",
    "Hong Kong": "HKD",
    "India": "INR",
    "Indonesia": "IDR",
    "Iran": "IRR",
    "Iraq": "IQD",
    "Israel": "ILS",
    "Jamaica": "JMD",
    "Japan": "JPY",
    "Jordan": "JOD",
    "Kenya": "KES",
    "Kiribati": "AUD",
    "Kuwait": "KWD",
    "Kyrgyzstan": "KGS",
    "Laos": "LAK",
    "Lebanon": "LBP",
    "Lesotho": "LSL",
    "Liberia": "LRD",
    "Libya": "LYD",
    "Madagascar": "MGA",
    "Malawi": "MWK",
    "Malaysia": "MYR",
    "Maldives": "MVR",
    "Mali": "XOF",
    "Marshall Islands": "USD",
    "Mauritania": "MRU",
    "Mauritius": "MUR",
    "Mexico": "MXN",
    "Micronesia": "USD",
    "Mongolia": "MNT",
    "Morocco": "MAD",
    "Mozambique": "MZN",
    "Myanmar": "MMK",
    "Namibia": "NAD",
    "Nauru": "AUD",
    "Nepal": "NPR",
    "New Zealand": "NZD",
    "Nicaragua": "NIO",
    "Niger": "XOF",
    "Nigeria": "NGN",
    "North Korea": "KPW",
    "Oman": "OMR",
    "Pakistan": "PKR",
    "Palau": "USD",
    "Panama": "PAB",
    "Papua New Guinea": "PGK",
    "Paraguay": "PYG",
    "Peru": "PEN",
    "Philippines": "PHP",
    "Qatar": "QAR",
    "Rwanda": "RWF",
    "Saint Kitts and Nevis": "XCD",
    "Saint Lucia": "XCD",
    "Saint Vincent and the Grenadines": "XCD",
    "Samoa": "WST",
    "Sao Tome and Principe": "STN",
    "Saudi Arabia": "SAR",
    "Senegal": "XOF",
    "Seychelles": "SCR",
    "Sierra Leone": "SLE",
    "Singapore": "SGD",
    "Solomon Islands": "SBD",
    "Somalia": "SOS",
    "South Africa": "ZAR",
    "South Korea": "KRW",
    "South Sudan": "SSP",
    "Sri Lanka": "LKR",
    "Sudan": "SDG",
    "Suriname": "SRD",
    "Syria": "SYP",
    "Taiwan": "TWD",
    "Tajikistan": "TJS",
    "Tanzania": "TZS",
    "Thailand": "THB",
    "Togo": "XOF",
    "Tonga": "TOP",
    "Trinidad and Tobago": "TTD",
    "Tunisia": "TND",
    "Turkmenistan": "TMT",
    "Tuvalu": "AUD",
    "Uganda": "UGX",
    "United Arab Emirates": "AED",
    "United States": "USD",
    "Uruguay": "UYU",
    "Uzbekistan": "UZS",
    "Vanuatu": "VUV",
    "Venezuela": "VES",
    "Vietnam": "VND",
    "Yemen": "YER",
    "Zambia": "ZMW",
    "Zimbabwe": "ZWL"
};



export default function currencyMap(country: string) {
    return countryCurrency[country];
}